---
- hosts: webservers
  become: true
  tasks:
    - name: Delete index.html file
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Upload application file and notify apache handler to restart
      copy:
        src: index.php
        dest: /var/www/html
        mode: 0755
      notify:
        - Restart Apache
  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
