---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: app
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: jnlp
  selector:
    app: jenkins
